### ISSUE TITLE
Implementation issue for superinterface contravariance error Q1'19

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#113]
This issue is for tracking implementation of the error raised for non-covariant occurrences of a type variable in a superinterface of a generic class:

Request issue: https://github.com/dart-lang/language/issues/38
Feature issue: https://github.com/dart-lang/language/issues/39

Feature specification:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/contravariant-superinterface-2018/feature-specification.md

Implementation plan:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/contravariant-superinterface-2018/implementation-plan.md

ETA: Q1 2019 in Dart Repo.

Breaking change request: https://github.com/dart-lang/sdk/issues/35097

### Phase 0:

- [x] Implementation in Analyzer (https://github.com/dart-lang/sdk/issues/35553)
- [x] Implementation in CFE/Kernel (https://github.com/dart-lang/sdk/issues/35792)
- [x] Implementation in Dart2js (TODO)
- [x] Implementation in DDC (TODO)
- [x] Write language tests (https://github.com/dart-lang/sdk/issues/36231)
- [x] Implementation in Intellij (TODO)

### Phase 1:

- [x] Language Specification Update (#387)
- [ ] Issue for updating documentation (TODO)
- [x] Announcement (TODO)

**Comment by mit-mit** [comment]
Associated breaking change request: https://github.com/dart-lang/sdk/issues/35097

**Comment by leafpetersen** [comment]
@kmillikin @stereotype441 Any updates on schedule?  Still on track for Q1?  Is there a tracking issue for the CFE?

**Comment by kmillikin** [comment]
There's no tracking issue for the CFE.  It's still on track for Q1 in the sense that our estimate is that it's a week's worth of work.  It's not on track for Q1 in the sense that we haven't started it so we're 0% completed at this time.

**Comment by kmillikin** [comment]
Filed https://github.com/dart-lang/sdk/issues/35792

**Comment by stereotype441** [comment]
The analyzer is in a similar situation - we haven't started, but it should take no more than a week's worth of work, and we expect to be able to get to it this quarter.

**Comment by leafpetersen** [comment]
@eernstg Are there any language tests for this?

**Comment by eernstg** [comment]
I do think we have language tests for this. I'll write some; changed the initial text of this issue to include a link to the issue.

**Comment by eernstg** [comment]
Language tests for this landed as 2805a376b2a5de4eceaec7617ae68b572ed91f29.

**Comment by leafpetersen** [comment]
cc @kevmoo 

This has landed in bleeding edge, for both CFE and analyzer.
