### ISSUE TITLE
Implementation tracking/meta Issue for Super Mixins 

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/language#12]
This issue is for tracking implementation of Super Mixins:

- Request issue: https://github.com/dart-lang/language/issues/6
- Feature issue: https://github.com/dart-lang/language/issues/7
- Feature specification: 
https://github.com/dart-lang/language/blob/master/accepted/2.1/super-mixins/feature-specification.md
 - Implementation plan: https://github.com/dart-lang/language/blob/master/accepted/2.1/super-mixins/implementation-plan.md

## TODO/Dependencies 

- [X] Discussion and feedback
  - General discussion: https://github.com/dart-lang/language/issues/7
  - Breaking change: https://github.com/dart-lang/language/issues/10
  - Syntax: https://github.com/dart-lang/language/issues/9
- [x] Implementation team sign off (this issue):

P0 Blockers
- [x] [Issue for language tests](https://github.com/dart-lang/sdk/issues/34385)
- [x] [Issue for implementation in Analyzer](https://github.com/dart-lang/sdk/issues/34164)
  - [x] [Mixin inference](https://github.com/dart-lang/sdk/issues/34404)
- [ ] [Issue for implementation in CFE/Kernel](https://github.com/dart-lang/sdk/issues/34165)
- [x] [Issue for implementation in VM](https://github.com/dart-lang/sdk/issues/34166)
- [x] [Issue for implementation in Intellij](https://github.com/dart-lang/sdk/issues/34169)
- [x] [Issue for implementation in Grok](https://buganizer.corp.google.com/issues/112724938)
- [x] [Issue for implementation in Dartfmt](https://github.com/dart-lang/dart_style/issues/727)
- [ ] [Issue for implementation in Documentation/Website](https://github.com/dart-lang/site-www/issues/1086)
- [x] [Issue for linter](https://github.com/dart-lang/linter/issues/1132)
- [x] Issue for migration to flutter (@yjbanov)
- [ ] Issue for updating documentation (TODO)
- [x] [Issue for implementation in Dartdoc](https://github.com/dart-lang/dartdoc/issues/1752) [flutter](https://github.com/dart-lang/sdk/issues/34642)

P1 Blockers
- [ ] [Issue for co19 tests](https://github.com/dart-lang/sdk/issues/33484)
- [x] [Issue for implementation in dart2js](https://github.com/dart-lang/sdk/issues/34168)
- [x] [Issue for implementation in DDC](https://github.com/dart-lang/sdk/issues/34167)

Non-Blockers
- [x] Issue for [CodeMirror](https://github.com/codemirror/CodeMirror/blob/master/mode/dart/dart.js)
- [ ] [Issue for implementation in Dartpad](https://github.com/dart-lang/dart-pad/issues/850)
- [ ] Misc syntax:
    - [x] Dart-atom: https://github.com/dart-atom/dart/tree/master/grammars
    - [ ] github markdown

**Based on meta issue [template](https://github.com/dart-lang/language/blob/master/templates/implementation_meta_issue.txt)

**Comment by leafpetersen** [comment]
I have added an initial cut on an implementation plan [here](https://github.com/dart-lang/language/blob/master/accepted/super-mixins.md).  If you are an assignee of this bug, please review the implementation plan and the proposal itself (if needed), and provide any feedback and comments.  If you see no technical issues with the proposal, and believe that the implementation plan is reasonable, please LGTM the plan here in the issue tracker.

@a-siva for VM
@kmillikin for CFE
@munificent for dartfmt
@jwren for grok, intellij
@jcollins-g for dartdoc
@bwilkerson for analyzer
@devoncarew for dartpad
@kwalrath for documentation
@vsmenon for DDC
@johnniwinther for dart2js
@Hixie for flutter migration

cc @JekCharlsonYu @dgrove @lrhn @rakudrama @sigmundch

**Comment by leafpetersen** [comment]
cc @mit-mit @timsneath @kevmoo @sethladd @filiph

**Comment by leafpetersen** [comment]
Hmm.  I don't seem to be able to assign this issue to most of you, but if you're listed above, please take a look and sign off.

**Comment by kevmoo** [comment]
I guess you could have made a "sign-off" PR and have us all approve.

LGTM

**Comment by bwilkerson** [comment]
lgtm

**Comment by Hixie** [comment]
I believe @yjbanov has volunteered to do the Flutter migration.

**Comment by Hixie** [comment]
For Flutter our usual policy is to only allow one syntax at a time, and to require lints to force us onto the new syntax if we change the allowed syntax. I would feel more comfortable if Flutter was moved to the new syntax in phase 3 after the lint has been made available in phase 2. LGTM assuming that we do the migration on Flutter's side after we've got a lint to enforce it.

**Comment by leafpetersen** [comment]
@Hixie I'm happy to handle the migration however works best for you.  My worry was/is this: I can't give you a lint to change a *definition* of a super mixin to the new syntax, because I have no way of knowing what things are super mixins until they are *used*.  So the lint will fire on uses, not definitions.

So I think it would be bad to land the analyzer hint that tells you are *using* an old style super mixin before we fix flutter.  Otherwise users will see hints telling them to fix flutter... :)

But we should be able to land them (essentially) simultaneously: migrate flutter to the new syntax and roll in a new analyzer with the hint.  Or maybe we can roll in the new analyzer, but initially only turn on the hint inside of flutter?

Does this seem reasonable?

**Comment by Hixie** [comment]
What we normally do is implement the lint, roll that, then turn on the lint and fix the bugs it finds at the same time.

**Comment by devoncarew** [comment]
Based on the above discussion, we should also call out above the necessary work in the linter.

**Comment by leafpetersen** [comment]
If this is just about finding super mixin definitions in flutter, I'm not sure investing in a lint is worthwhile.  I can find and fix all of the super-mixins *in flutter* independently.  

For flutter users, having a period where we a lint or hint fires is useful since it gives them time to make sure that packages get fixed.

My only concern with doing this as a lint is that removing the lint after it has served its purpose is essentially breaking, right (because people might reference it in their analysis_options.yaml)?  Whereas a hint (which has no external surface area) doesn't break anything if we remove it.  Or does the analyze ignore unknown lint names?

**Comment by bwilkerson** [comment]
The analyzer ignores unknown lint names, except when explicitly analyzing the analysis options file, in which case an error is generated.

**Comment by leafpetersen** [comment]
> The implementation plan mentions parsing in the CFE but not the analyzer front end. Is analyzer on the CFE now? Will we need to implement the syntax in the old analyzer parser?

Analyzer on CFE will happen before Phase 0.



> If we're only implementing this in the new front end, I need to make sure dartfmt is migrated to use analyzer+CFE. (Maybe there isn't any migration required and analyzer still exposes the exact same API and ASTs?)

@bwilkerson ?





> I don't see a TODO for tests. :) Who owns that?

Language team will land an initial set of tests, co19 will land a more exhaustive set.  I'll update appropriately.

**Comment by bwilkerson** [comment]
> Is analyzer on the CFE now?

Not yet, no ...

> Will we need to implement the syntax in the old analyzer parser?

... but we should be on the fasta parser by early next week (or maybe even the end of this week), so no.

> Maybe there isn't any migration required and analyzer still exposes the exact same API and ASTs?

Correct. When we move to the fasta parser (and later to CFE) the AST will not change. There might be a few minimal changes to the element model, but that won't effect dart_style.

> We'll want to get dartfmt support in pretty early because it will be hard for anyone to try the new syntax without that.

I have a CL out to add the AST structures we'll need: https://dart-review.googlesource.com/c/sdk/+/70141. It's a breaking change, though, so I'm not sure exactly when we want to commit it.

**Comment by munificent** [comment]
Sounds great, @bwilkerson! As long as there's a dartfmt tracking bug, I'll get it working with the new syntax once analyzer has the ASTs for it and is on CFE.

**Comment by bwilkerson** [comment]
Will you need a published version of analyzer to get started, or only after you're ready to publish dart_style?

> ... and is on CFE.

And the fasta parser supports the new syntax (which will likely be a bit after analyzer is using the fasta parser).

**Comment by munificent** [comment]
> Will you need a published version of analyzer to get started, or only after you're ready to publish dart_style?

A published one, preferably. Otherwise, there is no easy way to run dart_style's tests in its own repo or on Travis.

**Comment by Hixie** [comment]
Oh I guess if the lint is only valid for a short time anyway because the whole syntax is going away, then that's fine too. No need for a lint at all then. Just make the change to the syntax and fix Flutter at the same time. Or whatever works for you. Just beware that for the span of time between fixing Flutter and making it impossible to do it wrong, there will almost certainly be people who check in the wrong thing accidentally.

**Comment by leafpetersen** [comment]
> Oh I guess if the lint is only valid for a short time anyway because the whole syntax is going away, then that's fine too.

Actually, this raises a legitimate question.  The old way of writing *super-mixins* is going away.  But the old way of writing ordinary mixins will be supported indefinitely, and so there will be two ways to write a non-super mixin: using a mixin declaration or a class declaration.  If Flutter wants to migrate to a single syntax for all mixins, then we probably do want a long term supported lint for this.  @Hixie do you expect to want to migrate all mixins?

**Comment by devoncarew** [comment]
Just to clarify from above, we expect the analyzer to be using the fasta parser shortly (there are two blocking bugs in the sdk repo, and we have to re-check the status of that change rolling into google3). Analyzer on the full CFE (including resolution, not just using the parser), has an ETA on the order of months.

**Comment by bwilkerson** [comment]
> If Flutter wants to migrate to a single syntax for all mixins, then we probably do want a long term supported lint for this.

Or if we think that other users will want to use a single syntax :-)

Even without a lint we ought to have "convert class to mixin" and "convert mixin to class" assists.

**Comment by Hixie** [comment]
I could imagine desiring a lint along the lines of "only mix in classes declared with `mixin`", or a lint along the lines of "don't use `mixin` without an `on` clause". Certainly a goal of keeping things consistent throughout would be very nice.

We would probably just have a hack that requires that uses of the word "mixin" outside a comment are always followed by an identifier followed by the word "on", at least until we get a lint, to ensure that everything uses a single syntax. (We have many such tests already, e.g. one to verify we don't depend on package:test directly, one to verify that we are running the analyzer against the sample code in comments, one to verify that our internal imports don't form a cycle, etc.)

**Comment by leafpetersen** [comment]
> I could imagine desiring a lint along the lines of "only mix in classes declared with mixin",

This is consistent with our long term goals for the language, so how about we go with adding this lint to the analyzer in Phase 1, and then turning it on in flutter and fixing all the things in Phase 2?

**Comment by Hixie** [comment]
Sounds great.

**Comment by johnniwinther** [comment]
LGTM

**Comment by vsmenon** [comment]
lgtm for ddc

**Comment by keertip** [comment]
@leafpetersen, don't see any mention of rolling this into google3. Does it look like there will be no/few changes to the existing code base?

**Comment by leafpetersen** [comment]
@keertip This comment describes all uses in google3: https://github.com/dart-lang/language/issues/10#issuecomment-411928087 .  I don't expect any difficulties.
