### ISSUE TITLE
Implement "Spread Collections"

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#164]
The "Spread Collections" proposal (#47) has been accepted and is being implemented (yay!). This is the parent issue to track all of the specific issues for implementing the feature across various tools and libraries.

### Phase 0: Prerequisite

- [x] Experimental flag (TODO)
- [x] Language tests (TODO)

### Phase 1: Foundation

- [x] Implementation in CFE/Kernel (No tracking bug, feature is implemented)
- [ ] Implementation in analyzer (https://github.com/dart-lang/sdk/issues/35569)

### Phase 2: Tool implementation

- [x] Implementation in dart2js (https://github.com/dart-lang/sdk/issues/36313)
- [x] Implementation in dartfmt (https://github.com/dart-lang/dart_style/issues/778)
- [x] Implementation in dartdevc (https://github.com/dart-lang/sdk/issues/36006)
- [ ] Implementation in IntelliJ (TODO)
- [ ] Implementation in Grok (TODO)
- [ ] Implementation in analyzer (https://github.com/dart-lang/sdk/issues/35570)
- [x] Implementation in VM (https://github.com/dart-lang/sdk/issues/36218)
- [ ] Co19 tests (TODO)

### Phase 3: Release

- [ ] Enable (TODO)
- [ ] Use in SDK and team-maintained packages (TODO)
- [ ] Documentation (TODO)

### Phase 4: Clean-up

- [ ] Remove flag (TODO)

**Comment by munificent** [comment]
Note this open question: https://github.com/dart-lang/language/issues/167

**Comment by munificent** [comment]
A first batch of tests are out for review here: https://dart-review.googlesource.com/c/sdk/+/89085

**Comment by munificent** [comment]
dartfmt support is landed in the dart_style repo, but not published and rolled into the SDK yet. I'll do that once, I can upgrade it to analyzer 0.36.0.

**Comment by leafpetersen** [comment]
Is this complete?  Can we close this?

**Comment by munificent** [comment]
Yes!
