### ISSUE TITLE
Implement "Control Flow Collections"

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#165]
The "Control Flow Collections" proposal (#78) has been accepted and is being implemented (yay!). This is the parent issue to track all of the specific issues for implementing the feature across various tools and libraries.

### Phase 0: Prerequisite

- [x] Experimental flag
- [x] Language tests

### Phase 1: Foundation

- [x] Implementation in CFE/Kernel (https://github.com/dart-lang/sdk/issues/36333)
- [ ] Implementation in analyzer (https://github.com/dart-lang/sdk/issues/35566)

### Phase 2: Tool implementation

- [x] Implementation in dart2js (https://github.com/dart-lang/sdk/issues/36313)
- [x] Implementation in dartdevc (https://github.com/dart-lang/sdk/issues/36005)
- [x] Implementation in dartfmt (https://github.com/dart-lang/dart_style/issues/779)
- [ ] Implementation in IntelliJ (TODO)
- [ ] Implementation in Grok (TODO)
- [x] Implementation in analyzer (https://github.com/dart-lang/sdk/issues/35567)
- [ ] Implementation in Atom plugin (TODO)
- [x] Implementation in VM (https://github.com/dart-lang/sdk/issues/36214)
- [x] Co19 tests
- [x] Usability validation

### Phase 3: Release

- [ ] Enable (TODO)
- [ ] Use in SDK and team-maintained packages (TODO)
- [x] Documentation (https://medium.com/dartlang/making-dart-a-better-language-for-ui-f1ccaf9f546c)

### Phase 4: Clean-up

- [ ] Remove flag (TODO)

**Comment by munificent** [comment]
dartfmt support is landed in the dart_style repo, but not published and rolled into the SDK yet. I'll do that once, I can upgrade it to analyzer 0.36.0.

**Comment by leafpetersen** [comment]
Is this complete?  Can we close this?

**Comment by natebosch** [comment]
> Is this complete? Can we close this?

I don't think so: One of the steps is use in the SDK and/or team owned packages. Can you point to a usage?

We also need to add a step to validate behavior in codegen like angular. That is currently broken. Where is the template for these issues so I can add a step?

**Comment by natebosch** [comment]
The template has mentioned angular since [August 2018](https://github.com/dart-lang/language/commit/8f3bd9718711eeaaa6ba08d39725d7a54d7a7774). This issue was filed in January.

Why didn't we use the template?
If we did use the template, why did we delete the angular step?

**Comment by munificent** [comment]
I probably copy/pasted from an existing bug instead of from the template. I may not have known we even had the template. Sorry.

**Comment by munificent** [comment]
This has shipped!
