### ISSUE TITLE
Implementation issue for constant changes Q4'18

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/language#60]
This issue is for tracking implementation of a set of updates to the constant specification:

Request issue: https://github.com/dart-lang/language/issues/54
Feature issue: https://github.com/dart-lang/language/issues/61

Feature specification:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/feature-specification.md

Implementation plan:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/constant-update-2018/implementation-plan.md

ETA: Q4 2018 in Dart Repo.

Current Timing:
Phase 0: Mid November 2018
Phase 1: Early December 2018
Phase 2: Mid December 2018
Phase 3: Q1 2019

TODO/Dependencies [drafting and to be discussed with Leaf]

- [] Discussion and feedback
- [] Implementation team sign off (this issue):

*Phase 0 (Experimental Flags)
- [ ] [Experimental FlagsIssue for implementation in Analyzer](https://github.com/dart-lang/sdk/issues/35072)
- [ ] [Experimental FlagsIssue for implementation in CFE/Kernel]()
- [x] [Experimental FlagsIssue for implementation in Dart2JS](https://github.com/dart-lang/sdk/issues/35073)
- [x] [Experimental FlagsIssue for implementation in DDC](https://github.com/dart-lang/sdk/issues/35074)
- [ ] [Language Tests](https://github.com/dart-lang/language/issues/84)
- [ ] [Experimental FlagsIssue for implementation in Intellij](https://github.com/dart-lang/sdk/issues/35076)

*Phase 1  
- [ ] [Issue for implementation in Analyzer](https://github.com/dart-lang/sdk/issues/35080)
- [ ] [Issue for implementation in CFE/Kernel](https://github.com/dart-lang/sdk/issues/35079)
- [ ] [Issue for implementation in Intellij](https://github.com/dart-lang/sdk/issues/35078)
- [ ] [Issue for implementation in Grok](https://buganizer.corp.google.com/issues/119134253)
- [ ] [Issue for implementation in Dartfmt](https://github.com/dart-lang/dart_style/issues/748)
- [ ] [Issue for implementation in VM](https://github.com/dart-lang/sdk/issues/36220)
- [ ] [CO-19 Tests](https://github.com/dart-lang/co19/issues/185)
- [ ] [Issue for implementation in Dartdoc]()

*Phase 2 
- [ ] [Language Updates]()
- [ ] [Dart Doc]()

*Others:
- [ ] Issue for updating documentation (TODO)
- [ ] Comms / announcement (mit)

**Comment by JekCharlsonYu** [comment]
Sign offs doc here: 
https://docs.google.com/document/d/1brDDy48djKx4eWp8r_2u0rPD-vrrUE4U5QHi1r8nfqA/edit#

**Comment by a-siva** [comment]
@lrhn should the milestone for this issue be moved to 2.3, I don't think this feature is fully implemented correct.

**Comment by lrhn** [comment]
The CFE is still working on the feature. I hope it will make it into 2.3. If not, and we want to launch 2.3 anyway, we'll take it from there.

**Comment by leafpetersen** [comment]
Moving to 2.4
