### ISSUE TITLE
(Meta) Implementation issue for Set Literals Q4'18

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/language#90]
This issue is for tracking implementation of Set Literals:

Request issue: #36
Feature issue: #37 

[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md)
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)
[Sign off Doc](https://docs.google.com/document/d/1rUr2yXjos6phSd2cOaI8Qeh5RfpWm8o3SdnrOhKbQJs/edit#heading=h.lctzzkqehq3y)

Schedule ***TBD*****
Completion goals for the phases:

Task0: Mid November 2018
Task1: November 16, 2018
Task2, Task3: November 30, 2018
Tasks 4-14: December 14, 2018
Task15: December 21, 2018
Task16: January, 2019

--------------------

Task0 (Prerequisite)
Covered in [Constants Issue Tracker](https://github.com/dart-lang/language/issues/60)
Task1 : Task0 (Parsing support)
- [x] [The CFE implements parsing support for the new literal syntax](https://github.com/dart-lang/sdk/issues/35121)

Task2 : Task1 (CFE implementation)
- [x] [The CFE implements support for set literals](https://github.com/dart-lang/sdk/issues/35122)

Task3 : Task1 (Analyzer implementation)
- [x] [The analyzer implements static checking for set literals](https://github.com/dart-lang/sdk/issues/35120)

Task4 : Task3 (DDC implementation)
- [x] [DDC implements backend support](https://github.com/dart-lang/sdk/issues/35123)

Task5 : Task2 (VM support)
- [ ] [VM implements backend support](https://github.com/dart-lang/sdk/issues/35124)

Task6 : Task2 (dart2js support)
- [x] [dart2js implements backend support](https://github.com/dart-lang/sdk/issues/35125)

Task7 : Task0 (Intellij support)
- [x] [IntelliJ parser supports set literals](https://github.com/dart-lang/sdk/issues/35126)

Task8 : Task1 (Grok support)
- [ ] [Grok implements any required support](https://buganizer.corp.google.com/issues/119323667)

Task9 : Task3 (Dartfmt support)
- [x] [Dartfmt implements formatting support](https://github.com/dart-lang/dart_style/issues/751)

Task9 : Task3 (Dartdoc support)
- [x] [Dartdoc implements support](https://github.com/dart-lang/dartdoc/issues/1826)

Task10 : (Specification)
- [x] [Add set literals to formal spec]

Task11 : (Documentation)
- [x] [Document in language references]

Task12 : (co19 tests)
- [x] [co19 tests written](https://github.com/dart-lang/co19/issues/188)

Task13 : (Language tests)
- [x] [Language tests written](https://github.com/dart-lang/language/issues/91)

Task14 : Task1 (Angular compiler, sourcegen)
- [x] [Angular compiler and sourcegen clients support set literals]()

Task15 : Task14 (Google3 roll)
- [x] [Roll to google3 with flag enabled]

Task16 : * (Launch)
- [x] [Remove the experimental flag, enable by default, announce the feature]()

**Comment by JekCharlsonYu** [comment]
@mit-mit @leafpetersen

**Comment by munificent** [comment]
Dartfmt support is published and rolled into the SDK as of: https://dart-review.googlesource.com/c/sdk/+/86581
